version: '3.8'

services:
  umbrel-lightning:
    image: lightninglabs/lnd:v0.19.2-beta@sha256:dd113dff920c309bf5c4af6a37d912f379dc24c51f266a2c878c12d20501798b
    container_name: umbrel-lightning
    ports:
      - "3002:3000"  # Web interface
      - "9735:9735"  # Lightning P2P
      - "8080:8080"  # REST API
    environment:
      - LIGHTNING_NETWORK=bitcoin
      - LIGHTNING_BITCOIN_RPC_HOST=umbrel-bitcoin
      - LIGHTNING_BITCOIN_RPC_PORT=8332
      - LIGHTNING_BITCOIN_RPC_USER=umbrel
      - LIGHTNING_BITCOIN_RPC_PASSWORD=moneyprintergobrrr
      - LIGHTNING_BITCOIN_RPC_PROTOCOL=http
      - LIGHTNING_ALIAS=Umbrel Lightning
      - LIGHTNING_COLOR=3399FF
      - LIGHTNING_WEB_PORT=3000
      - LIGHTNING_P2P_PORT=9735
      - LIGHTNING_REST_PORT=8080
      - LIGHTNING_LOG_LEVEL=info
      # Tor Configuration
      - TOR_PROXY_IP=umbrel-tor
      - TOR_PROXY_PORT=9050
    volumes:
      - ./data:/home/lightning/.lightning
      # Unraid-specific volume mapping (commented out for local testing)
      # - /mnt/user/appdata/umbrel-lightning:/home/lightning/.lightning
    networks:
      - umbrel-network
    depends_on:
      - umbrel-bitcoin
      - umbrel-tor      # Tor daemon dependency
    restart: unless-stopped
    user: "1000:1000"  # nobody:users equivalent for Unraid
    # Alternative for Unraid: user: "99:100"

  # Optional Bitcoin node for testing (comment out if using external Bitcoin node)
  umbrel-bitcoin:
    image: ghcr.io/getumbrel/umbrel-bitcoin:v1.0.3-core.v29.0@sha256:311d14cf3cb0a49fad7779310521f1abd9242dfcc2f08eb8e3cbff97ca67d6ea
    container_name: umbrel-bitcoin
    ports:
      - "8332:8332"  # RPC
      - "8333:8333"  # P2P
      - "18332:18332"  # testnet RPC
      - "18333:18333"  # testnet P2P
    environment:
      - BITCOIN_NETWORK=bitcoin
      - BITCOIN_RPC_USER=umbrel
      - BITCOIN_RPC_PASSWORD=moneyprintergobrrr
      - BITCOIN_RPC_BIND=0.0.0.0:8332
      - BITCOIN_RPC_ALLOW_IP=0.0.0.0/0
      - BITCOIN_DISABLE_WALLET=0
      - BITCOIN_TXINDEX=1
      - BITCOIN_BLOCKFILTERINDEX=1
      - BITCOIN_PRUNING=0
    volumes:
      - ./bitcoin-data:/home/umbrel/.bitcoin
      # Unraid-specific volume mapping (commented out for local testing)
      # - /mnt/user/appdata/umbrel-bitcoin:/home/umbrel/.bitcoin
    networks:
      - umbrel-network
    restart: unless-stopped
    user: "1000:1000"  # nobody:users equivalent for Unraid
    # Alternative for Unraid: user: "99:100"

  umbrel-tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    container_name: umbrel-lightning-tor
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ./torrc:/etc/tor/torrc:ro
      - ./tor-data:/data
    environment:
      HOME: "/tmp"
    networks:
      umbrel-network:
        ipv4_address: 172.22.0.2

networks:
  umbrel-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

volumes:
  data:
  bitcoin-data:
