version: '3.8'

services:
  umbrel-monero:
    image: ghcr.io/sethforprivacy/simple-monerod:v0.18.4.1@sha256:11810da93d3a92721421e7aa5f6e1763e12752d5398b84659d864cccc3ebe989
    container_name: umbrel-monero
    ports:
      - "18089:18089"  # RPC
      - "18090:18090"  # P2P
      - "18091:18091"  # ZMQ RPC
      - "18092:18092"  # ZMQ PUB
    environment:
      - MONERO_NETWORK=mainnet
      - MONERO_RPC_BIND_IP=0.0.0.0
      - MONERO_RPC_BIND_PORT=18089
      - MONERO_P2P_BIND_IP=0.0.0.0
      - MONERO_P2P_BIND_PORT=18090
      - MONERO_ZMQ_RPC_BIND_IP=0.0.0.0
      - MONERO_ZMQ_RPC_BIND_PORT=18091
      - MONERO_ZMQ_PUB_BIND_IP=0.0.0.0
      - MONERO_ZMQ_PUB_BIND_PORT=18092
      - MONERO_RPC_LOGIN=monero:moneyprintergobrrr
      - MONERO_RESTRICTED_RPC=1
      - MONERO_DISABLE_RPC_LOGIN=0
      - MONERO_SYNC_MODE=fast
      - MONERO_PRUNING=0
      - MONERO_DB_SALVAGE=0
      - MONERO_MAX_CONCURRENCY=0
      - MONERO_PREPARE_MULTISIG=0
      - MONERO_OFFLINE=0
      - MONERO_DATA_DIR=/home/monero/.bitmonero
      - MONERO_LOG_LEVEL=1
      # Tor and I2P Configuration
      - TOR_PROXY_IP=umbrel-tor
      - TOR_PROXY_PORT=9050
      - TOR_PROXY_CONTROL_PORT=9051
      - TOR_PROXY_CONTROL_PASSWORD=moneyprintergobrrr
      - I2P_DAEMON_IP=umbrel-i2pd
      - I2P_DAEMON_PORT=7656
    volumes:
      - ./data:/home/monero/.bitmonero
      # Unraid-specific volume mapping (commented out for local testing)
      # - /mnt/user/appdata/umbrel-monero:/home/monero/.bitmonero
    networks:
      - monero-network
    restart: unless-stopped
    depends_on:
      - umbrel-tor
      - umbrel-i2pd
    user: "1000:1000"  # nobody:users equivalent for Unraid
    # Alternative for Unraid: user: "99:100"

  umbrel-tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    container_name: umbrel-monero-tor
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ./torrc:/etc/tor/torrc:ro
      - ./tor-data:/data
    environment:
      HOME: "/tmp"
    networks:
      monero-network:
        ipv4_address: 172.23.0.2

  umbrel-i2pd:
    image: purplei2p/i2pd:release-2.44.0@sha256:d154a599793c393cf9c91f8549ba7ece0bb40e5728e1813aa6dd4c210aa606f6
    container_name: umbrel-monero-i2pd
    user: "root"
    command: --sam.enabled=true --sam.address=0.0.0.0 --sam.port=7656 --loglevel=error
    restart: on-failure
    volumes:
      - ./i2pd-data:/home/i2pd/data
    networks:
      monero-network:
        ipv4_address: 172.23.0.3

networks:
  monero-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16

volumes:
  data:
