version: '3.8'

services:
  umbrel-bitcoin:
    image: ghcr.io/getumbrel/umbrel-bitcoin:v1.0.3-core.v29.0@sha256:311d14cf3cb0a49fad7779310521f1abd9242dfcc2f08eb8e3cbff97ca67d6ea
    container_name: umbrel-bitcoin
    restart: unless-stopped
    ports:
      - "8332:8332"  # Bitcoin RPC (mainnet)
      - "8333:8333"  # Bitcoin P2P (mainnet)
      - "18332:18332"  # Bitcoin RPC (testnet)
      - "18333:18333"  # Bitcoin P2P (testnet)
      - "3000:3000"  # Web UI
    volumes:
      - ./data:/data
      # Unraid-specific volume mapping (uncomment for production use)
      # - /mnt/user/appdata/umbrel-bitcoin:/data
    environment:
      - BITCOIN_NETWORK=mainnet
      - BITCOIN_RPC_USER=umbrel
      - BITCOIN_RPC_PASSWORD=moneyprintergobrrr
      - BITCOIN_RPC_BIND=0.0.0.0
      - BITCOIN_RPC_ALLOW_IP=0.0.0.0/0
      - BITCOIN_DISABLE_WALLET=1
      - BITCOIN_TXINDEX=1
      - BITCOIN_BLOCKFILTERINDEX=1
      - BITCOIN_PRUNING=0
      - BITCOIN_DBCACHE=450
      - BITCOIN_MAXMEMPOOL=300
      - BITCOIN_MAXCONNECTIONS=125
      - BITCOIN_MAXUPLOADTARGET=5000
      - BITCOIN_COINSTATSINDEX=1
      - BITCOIN_MEMPOOLEXPIRY=336
      - BITCOIN_PAR=0
      - BITCOIND_EXTRA_ARGS=-deprecatedrpc=create_bdb
    user: "1000:1000"  # Unraid nobody:users equivalent
    # Alternative user mapping for Unraid
    # user: "99:100"  # nobody:users on Unraid

networks:
  default:
    driver: bridge
