version: '3.8'

services:
  umbrel-bitcoin:
    image: ghcr.io/getumbrel/umbrel-bitcoin:v1.0.3-core.v29.0@sha256:311d14cf3cb0a49fad7779310521f1abd9242dfcc2f08eb8e3cbff97ca67d6ea
    container_name: umbrel-bitcoin
    restart: unless-stopped
    ports:
      - "8332:8332"  # Bitcoin RPC (mainnet)
      - "8333:8333"  # Bitcoin P2P (mainnet)
      - "18332:18332"  # Bitcoin RPC (testnet)
      - "18333:18333"  # Bitcoin P2P (testnet)
      - "3000:3000"  # Web UI
    volumes:
      - ./data:/data
      # Unraid-specific volume mapping (uncomment for production use)
      # - /mnt/user/appdata/umbrel-bitcoin:/data
    environment:
      - BITCOIN_NETWORK=mainnet
      - BITCOIN_RPC_USER=umbrel
      - BITCOIN_RPC_PASSWORD=moneyprintergobrrr
      - BITCOIN_RPC_BIND=0.0.0.0
      - BITCOIN_RPC_ALLOW_IP=0.0.0.0/0
      - BITCOIN_DISABLE_WALLET=1
      - BITCOIN_TXINDEX=1
      - BITCOIN_BLOCKFILTERINDEX=1
      - BITCOIN_PRUNING=0
      - BITCOIN_DBCACHE=450
      - BITCOIN_MAXMEMPOOL=300
      - BITCOIN_MAXCONNECTIONS=125
      - BITCOIN_MAXUPLOADTARGET=5000
      - BITCOIN_COINSTATSINDEX=1
      - BITCOIN_MEMPOOLEXPIRY=336
      - BITCOIN_PAR=0
      - BITCOIND_EXTRA_ARGS=-deprecatedrpc=create_bdb
      # Tor and I2P Configuration
      - TOR_HOST=umbrel-tor
      - TOR_SOCKS_PORT=9050
      - TOR_CONTROL_PORT=9051
      - TOR_CONTROL_PASSWORD=moneyprintergobrrr
      - I2P_HOST=umbrel-i2pd
      - I2P_SAM_PORT=7656
    user: "1000:1000"  # Unraid nobody:users equivalent
    # Alternative user mapping for Unraid
    # user: "99:100"  # nobody:users on Unraid
    depends_on:
      - umbrel-tor
      - umbrel-i2pd

  umbrel-tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    container_name: umbrel-tor
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ./torrc:/etc/tor/torrc:ro
      - ./tor-data:/data
    environment:
      HOME: "/tmp"
    networks:
      default:
        ipv4_address: 172.20.0.2

  umbrel-i2pd:
    image: purplei2p/i2pd:release-2.44.0@sha256:d154a599793c393cf9c91f8549ba7ece0bb40e5728e1813aa6dd4c210aa606f6
    container_name: umbrel-i2pd
    user: "root"
    command: --sam.enabled=true --sam.address=0.0.0.0 --sam.port=7656 --loglevel=error
    restart: on-failure
    volumes:
      - ./i2pd-data:/home/i2pd/data
    networks:
      default:
        ipv4_address: 172.20.0.3

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
