version: '3.8'

services:
  umbrel-bitcoin:
    build: .
    container_name: umbrel-bitcoin
    restart: unless-stopped
    ports:
      - "8332:8332"  # Bitcoin RPC (mainnet)
      - "8333:8333"  # Bitcoin P2P (mainnet)
      - "18332:18332"  # Bitcoin RPC (testnet)
      - "18333:18333"  # Bitcoin P2P (testnet)
    volumes:
      - ./data:/home/umbrel/.bitcoin
      # Unraid-specific volume mapping (uncomment for production use)
      # - /mnt/user/appdata/umbrel-bitcoin:/home/umbrel/.bitcoin
    environment:
      - BITCOIN_NETWORK=mainnet
      - BITCOIN_RPC_USER=umbrel
      - BITCOIN_RPC_PASSWORD=moneyprintergobrrr
      - BITCOIN_RPC_BIND=0.0.0.0
      - BITCOIN_RPC_ALLOW_IP=0.0.0.0/0
      - BITCOIN_DISABLE_WALLET=1
      - BITCOIN_TXINDEX=1
      - BITCOIN_BLOCKFILTERINDEX=1
      - BITCOIN_PRUNING=0
      # Tor Configuration
      - TOR_HOST=umbrel-tor
      - TOR_SOCKS_PORT=9050
      - TOR_CONTROL_PORT=9051
      - TOR_CONTROL_PASSWORD=moneyprintergobrrr
      # I2P Configuration
      - I2P_HOST=umbrel-i2pd
      - I2P_SAM_PORT=7656
    networks:
      - bitcoin-network
    user: "1000:1000"  # Unraid nobody:users equivalent
    # Alternative user mapping for Unraid
    # user: "99:100"  # nobody:users on Unraid
    depends_on:
      - umbrel-tor
      - umbrel-i2pd

  umbrel-tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    container_name: umbrel-tor
    restart: unless-stopped
    ports:
      - "9050:9050"  # Tor SOCKS proxy
      - "9051:9051"  # Tor control port
    volumes:
      - ./torrc:/etc/tor/torrc:ro
      - ./tor-data:/data
    environment:
      - HOME=/tmp
    networks:
      - bitcoin-network
    user: "1000:1000"

  umbrel-i2pd:
    image: purplei2p/i2pd:release-2.44.0@sha256:d154a599793c393cf9c91f8549ba7ece0bb40e5728e1813aa6dd4c210aa606f6
    container_name: umbrel-i2pd
    restart: unless-stopped
    ports:
      - "7656:7656"  # I2P SAM protocol
    volumes:
      - ./i2pd-data:/home/i2pd/data
    command: --sam.enabled=true --sam.address=0.0.0.0 --sam.port=7656 --loglevel=error
    networks:
      - bitcoin-network
    user: "1000:1000"

networks:
  bitcoin-network:
    driver: bridge
